BASEPATH = 'data/'
CSV = 'train.csv'
IMAGE_COUNT = 100
FEATURES_FILE_NAME = 'features'
FEATURES_PATH = f"{BASEPATH}{FEATURES_FILE_NAME}.npy"
LABELS_FILE_NAME = 'labels'
LABELS_PATH = f"{BASEPATH}{LABELS_FILE_NAME}.npy"
