BASEPATH = 'data/'
CSV = 'data/train.csv'
IMAGE_COUNT = 100
FEATURES_FILE_NAME = 'features_1000'
FEATURES_PATH = f"{BASEPATH}{FEATURES_FILE_NAME}.npy"
LABELS_FILE_NAME = 'labels_1000'
LABELS_PATH = f"{BASEPATH}{LABELS_FILE_NAME}.npy"
